vich_uploader:
    db_driver: orm


   # mappings:
    #    products:
            #uri_prefix: /images/products
     #       uri_prefix:  '%app.path.product_images%'
            #upload_destination: '%kernel.project_dir%/public/images/products'
      #      upload_destination: '%kernel.project_dir%/public%app.path.product_images%'

    mappings:
         product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true